onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /tb_buffer/clk
add wave -noupdate -radix hexadecimal /tb_buffer/busy
add wave -noupdate -radix hexadecimal /tb_buffer/reset
add wave -noupdate -radix hexadecimal /tb_buffer/buffermode
add wave -noupdate -radix hexadecimal /tb_buffer/wren_b
add wave -noupdate -radix hexadecimal /tb_buffer/hold_mode
add wave -noupdate -radix hexadecimal /tb_buffer/w_data
add wave -noupdate -radix hexadecimal /tb_buffer/addr_image
add wave -noupdate -radix hexadecimal -childformat {{{/tb_buffer/addr_kernal[14]} -radix hexadecimal} {{/tb_buffer/addr_kernal[13]} -radix hexadecimal} {{/tb_buffer/addr_kernal[12]} -radix hexadecimal} {{/tb_buffer/addr_kernal[11]} -radix hexadecimal} {{/tb_buffer/addr_kernal[10]} -radix hexadecimal} {{/tb_buffer/addr_kernal[9]} -radix hexadecimal} {{/tb_buffer/addr_kernal[8]} -radix hexadecimal} {{/tb_buffer/addr_kernal[7]} -radix hexadecimal} {{/tb_buffer/addr_kernal[6]} -radix hexadecimal} {{/tb_buffer/addr_kernal[5]} -radix hexadecimal} {{/tb_buffer/addr_kernal[4]} -radix hexadecimal} {{/tb_buffer/addr_kernal[3]} -radix hexadecimal} {{/tb_buffer/addr_kernal[2]} -radix hexadecimal} {{/tb_buffer/addr_kernal[1]} -radix hexadecimal} {{/tb_buffer/addr_kernal[0]} -radix hexadecimal}} -subitemconfig {{/tb_buffer/addr_kernal[14]} {-radix hexadecimal} {/tb_buffer/addr_kernal[13]} {-radix hexadecimal} {/tb_buffer/addr_kernal[12]} {-radix hexadecimal} {/tb_buffer/addr_kernal[11]} {-radix hexadecimal} {/tb_buffer/addr_kernal[10]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[9]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[8]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[7]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[6]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[5]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[4]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[3]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[2]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[1]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_kernal[0]} {-height 15 -radix hexadecimal}} /tb_buffer/addr_kernal
add wave -noupdate -radix hexadecimal -childformat {{{/tb_buffer/addr_conv[14]} -radix hexadecimal} {{/tb_buffer/addr_conv[13]} -radix hexadecimal} {{/tb_buffer/addr_conv[12]} -radix hexadecimal} {{/tb_buffer/addr_conv[11]} -radix hexadecimal} {{/tb_buffer/addr_conv[10]} -radix hexadecimal} {{/tb_buffer/addr_conv[9]} -radix hexadecimal} {{/tb_buffer/addr_conv[8]} -radix hexadecimal} {{/tb_buffer/addr_conv[7]} -radix hexadecimal} {{/tb_buffer/addr_conv[6]} -radix hexadecimal} {{/tb_buffer/addr_conv[5]} -radix hexadecimal} {{/tb_buffer/addr_conv[4]} -radix hexadecimal} {{/tb_buffer/addr_conv[3]} -radix hexadecimal} {{/tb_buffer/addr_conv[2]} -radix hexadecimal} {{/tb_buffer/addr_conv[1]} -radix hexadecimal} {{/tb_buffer/addr_conv[0]} -radix hexadecimal}} -subitemconfig {{/tb_buffer/addr_conv[14]} {-radix hexadecimal} {/tb_buffer/addr_conv[13]} {-radix hexadecimal} {/tb_buffer/addr_conv[12]} {-radix hexadecimal} {/tb_buffer/addr_conv[11]} {-radix hexadecimal} {/tb_buffer/addr_conv[10]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[9]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[8]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[7]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[6]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[5]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[4]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[3]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[2]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[1]} {-height 15 -radix hexadecimal} {/tb_buffer/addr_conv[0]} {-height 15 -radix hexadecimal}} /tb_buffer/addr_conv
add wave -noupdate -radix hexadecimal /tb_buffer/mat_row
add wave -noupdate -radix hexadecimal /tb_buffer/mat_col
add wave -noupdate -radix hexadecimal -childformat {{{/tb_buffer/kernal[8]} -radix hexadecimal} {{/tb_buffer/kernal[7]} -radix hexadecimal} {{/tb_buffer/kernal[6]} -radix hexadecimal} {{/tb_buffer/kernal[5]} -radix hexadecimal} {{/tb_buffer/kernal[4]} -radix hexadecimal} {{/tb_buffer/kernal[3]} -radix hexadecimal} {{/tb_buffer/kernal[2]} -radix hexadecimal} {{/tb_buffer/kernal[1]} -radix hexadecimal} {{/tb_buffer/kernal[0]} -radix hexadecimal}} -subitemconfig {{/tb_buffer/kernal[8]} {-height 15 -radix hexadecimal} {/tb_buffer/kernal[7]} {-height 15 -radix hexadecimal} {/tb_buffer/kernal[6]} {-height 15 -radix hexadecimal} {/tb_buffer/kernal[5]} {-height 15 -radix hexadecimal} {/tb_buffer/kernal[4]} {-height 15 -radix hexadecimal} {/tb_buffer/kernal[3]} {-height 15 -radix hexadecimal} {/tb_buffer/kernal[2]} {-height 15 -radix hexadecimal} {/tb_buffer/kernal[1]} {-height 15 -radix hexadecimal} {/tb_buffer/kernal[0]} {-height 15 -radix hexadecimal}} /tb_buffer/kernal
add wave -noupdate /tb_buffer/matched
add wave -noupdate -radix unsigned /tb_buffer/miss_matched
add wave -noupdate -radix hexadecimal -childformat {{{/tb_buffer/data_mat[8]} -radix hexadecimal} {{/tb_buffer/data_mat[7]} -radix hexadecimal} {{/tb_buffer/data_mat[6]} -radix hexadecimal} {{/tb_buffer/data_mat[5]} -radix hexadecimal} {{/tb_buffer/data_mat[4]} -radix hexadecimal} {{/tb_buffer/data_mat[3]} -radix hexadecimal} {{/tb_buffer/data_mat[2]} -radix hexadecimal} {{/tb_buffer/data_mat[1]} -radix hexadecimal} {{/tb_buffer/data_mat[0]} -radix hexadecimal}} -expand -subitemconfig {{/tb_buffer/data_mat[8]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat[7]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat[6]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat[5]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat[4]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat[3]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat[2]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat[1]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat[0]} {-height 15 -radix hexadecimal}} /tb_buffer/data_mat
add wave -noupdate -radix hexadecimal -childformat {{{/tb_buffer/data_mat_exp[8]} -radix hexadecimal} {{/tb_buffer/data_mat_exp[7]} -radix hexadecimal} {{/tb_buffer/data_mat_exp[6]} -radix hexadecimal} {{/tb_buffer/data_mat_exp[5]} -radix hexadecimal} {{/tb_buffer/data_mat_exp[4]} -radix hexadecimal} {{/tb_buffer/data_mat_exp[3]} -radix hexadecimal} {{/tb_buffer/data_mat_exp[2]} -radix hexadecimal} {{/tb_buffer/data_mat_exp[1]} -radix hexadecimal} {{/tb_buffer/data_mat_exp[0]} -radix hexadecimal}} -expand -subitemconfig {{/tb_buffer/data_mat_exp[8]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat_exp[7]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat_exp[6]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat_exp[5]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat_exp[4]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat_exp[3]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat_exp[2]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat_exp[1]} {-height 15 -radix hexadecimal} {/tb_buffer/data_mat_exp[0]} {-height 15 -radix hexadecimal}} /tb_buffer/data_mat_exp
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1379009 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {3560198 ps} {3742494 ps}
